Terminado
O programa Python terminou com erro (código de saída: 143). Reiniciando...
